services:
  # Backend Service
  - type: web
    name: workspace-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BASE_PATH
        value: /api
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
      - key: FRONTEND_GOOGLE_CALLBACK_URL
        sync: false

  # Frontend Service
  - type: static
    name: workspace-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: client
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
